## This code is used to get all the stock in LQ45 for GARP analysis

This code will scrape the reuters financial highlights web page to get all financial data to conduct the calculation. This code is used to get all the EPS for 1 year, EPS for 5 year and the P/E ratio. This code will then calculate the PEG (PE Ratio/PER)for all the LQ45 stocks. From the list, an investor can take conclusion for choosing best stock based on the GARP analysis.

The list of LQ45 has been previously got from the previous code.

In [10]:
#import library
import requests
from bs4 import BeautifulSoup
import urllib.request
import pandas as pd
import time

In [195]:
#importing file of LQ45 list that we have got before
df=pd.read_excel('lq45_list.xlsx')

In [35]:
df.sample(5)

      Idx                                Company
31   PTBA                        Bukit Asam Tbk.
29   MNCN             Media Nusantara Citra Tbk.
6    BBNI   Bank Negara Indonesia (Persero) Tbk.
2    AKRA                    AKR Corporindo Tbk.
41   UNVR                Unilever Indonesia Tbk.

In [17]:
df.count()

Idx        45
Company    45
dtype: int64

In [22]:
idxs=df['Idx']

In [23]:
url_lists=[]
for idx in idxs:
    url='https://www.reuters.com/finance/stocks/financial-highlights/'+idx+'.JK'
    url_lists.append(url)

In [24]:
url_lists_idx=url_lists

In [25]:
url_lists_idx

['https://www.reuters.com/finance/stocks/financial-highlights/ ADHI.JK',
 'https://www.reuters.com/finance/stocks/financial-highlights/ ADRO.JK',
 'https://www.reuters.com/finance/stocks/financial-highlights/ AKRA.JK',
 'https://www.reuters.com/finance/stocks/financial-highlights/ ANTM.JK',
 'https://www.reuters.com/finance/stocks/financial-highlights/ ASII.JK',
 'https://www.reuters.com/finance/stocks/financial-highlights/ BBCA.JK',
 'https://www.reuters.com/finance/stocks/financial-highlights/ BBNI.JK',
 'https://www.reuters.com/finance/stocks/financial-highlights/ BBRI.JK',
 'https://www.reuters.com/finance/stocks/financial-highlights/ BBTN.JK',
 'https://www.reuters.com/finance/stocks/financial-highlights/ BMRI.JK',
 'https://www.reuters.com/finance/stocks/financial-highlights/ BRPT.JK',
 'https://www.reuters.com/finance/stocks/financial-highlights/ BSDE.JK',
 'https://www.reuters.com/finance/stocks/financial-highlights/ CPIN.JK',
 'https://www.reuters.com/finance/stocks/financial-highlights/ ELSA.JK',
 'https://www.reuters.com/finance/stocks/financial-highlights/ ERAA.JK',
 'https://www.reuters.com/finance/stocks/financial-highlights/ EXCL.JK',
 'https://www.reuters.com/finance/stocks/financial-highlights/ GGRM.JK',
 'https://www.reuters.com/finance/stocks/financial-highlights/ HMSP.JK',
 'https://www.reuters.com/finance/stocks/financial-highlights/ ICBP.JK',
 'https://www.reuters.com/finance/stocks/financial-highlights/ INCO.JK',
 'https://www.reuters.com/finance/stocks/financial-highlights/ INDF.JK',
 'https://www.reuters.com/finance/stocks/financial-highlights/ INDY.JK',
 'https://www.reuters.com/finance/stocks/financial-highlights/ INKP.JK',
 'https://www.reuters.com/finance/stocks/financial-highlights/ INTP.JK',
 'https://www.reuters.com/finance/stocks/financial-highlights/ ITMG.JK',
 'https://www.reuters.com/finance/stocks/financial-highlights/ JSMR.JK',
 'https://www.reuters.com/finance/stocks/financial-highlights/ KLBF.JK',
 'https://www.reuters.com/finance/stocks/financial-highlights/ LPPF.JK',
 'https://www.reuters.com/finance/stocks/financial-highlights/ MEDC.JK',
 'https://www.reuters.com/finance/stocks/financial-highlights/ MNCN.JK',
 'https://www.reuters.com/finance/stocks/financial-highlights/ PGAS.JK',
 'https://www.reuters.com/finance/stocks/financial-highlights/ PTBA.JK',
 'https://www.reuters.com/finance/stocks/financial-highlights/ PTPP.JK',
 'https://www.reuters.com/finance/stocks/financial-highlights/ PWON.JK',
 'https://www.reuters.com/finance/stocks/financial-highlights/ SCMA.JK',
 'https://www.reuters.com/finance/stocks/financial-highlights/ SMGR.JK',
 'https://www.reuters.com/finance/stocks/financial-highlights/ SRIL.JK',
 'https://www.reuters.com/finance/stocks/financial-highlights/ TKIM.JK',
 'https://www.reuters.com/finance/stocks/financial-highlights/ TLKM.JK',
 'https://www.reuters.com/finance/stocks/financial-highlights/ TPIA.JK',
 'https://www.reuters.com/finance/stocks/financial-highlights/ UNTR.JK',
 'https://www.reuters.com/finance/stocks/financial-highlights/ UNVR.JK',
 'https://www.reuters.com/finance/stocks/financial-highlights/ WIKA.JK',
 'https://www.reuters.com/finance/stocks/financial-highlights/ WSBP.JK',
 'https://www.reuters.com/finance/stocks/financial-highlights/ WSKT.JK']

Creating function for all parameters needed. The function is get_soup : to get parsed soup element, get_price : get the latest price, get_time : get the current time, get_pe_now : get the current PE ratio, get_eps_1_year: get the last 1 year EPS, get_eps_3_year: get the last 3 year EPS, get_eps_5_year: get the last 5 year of EPS. 

NOTE: not all the function will be used

In [26]:
def get_soup():
    r=requests.get(url_list)
    soup=BeautifulSoup(r.text,'html.parser')
    return soup

def get_price():
    stock=get_soup().find_all('span',attrs={'class':""})[0]  #function in function
    stock=float(stock.text.strip().replace(',',''))          
    return stock

def get_time():
    time=soup.find('span',attrs={'class':'nasdaqChangeTime'}).text.strip()
    return time

def get_pe_now():
    pe=get_soup().find_all('tr',attrs={'class':'stripe'})[4]
    pe=pe.find_all('td',attrs={'class':'data'})[0].text.strip()
    return pe

def get_eps_1_year():
    eps_one_year=get_soup().find_all('tbody',attrs={'class':'dataSmall'})
    eps_one_year=eps_one_year[0].find_all('td')[5].text.strip()
    return eps_one_year

def get_eps_3_year():
    eps_three_year=get_soup().find_all('tbody',attrs={'class':'dataSmall'})
    eps_three_year=eps_three_year[0].find_all('td')[6].text.strip()
    return eps_three_year

def get_eps_5_year():
    eps_five_year=get_soup().find_all('tbody',attrs={'class':'dataSmall'})
    eps_five_year=eps_five_year[0].find_all('td')[7].text.strip()
    return eps_five_year

In [85]:
price_list=[]
eps_1=[]
eps_3=[]
eps_5=[]
per=[]
for url_list in url_lists_idx:
    get_soup()
    get_price()
    get_eps_1_year()
    price_list.append(get_price())
    eps_1.append(get_eps_1_year())
    eps_3.append(get_eps_3_year())
    eps_5.append(get_eps_5_year())
    per.append(get_pe_now())

In [88]:
df_financial=pd.DataFrame({'Stock Price':price_list,'PER':per,'EPS Growth 1 Yr':eps_1,'EPS Growth 3 Yr':eps_3,'EPS Growth 5 Year':eps_5})

In [99]:
df_financial.head(20)

    Stock Price     PER EPS Growth 1 Yr EPS Growth 3 Yr EPS Growth 5 Year
0        1610.0    1.61           44.12           -7.47              7.75
1        1450.0   11.02          119.37           12.67            -10.76
2        4740.0   26.98          -20.82          -11.95              1.46
3         960.0    0.52          102.24          -57.89            -56.34
4        7250.0   18.56            4.78           -7.93             -3.15
5       27525.0   23.38           14.36           13.04             13.48
6        9350.0   10.31           25.30            7.90             14.32
7        3990.0   15.08           11.70            8.70              8.87
8        2390.0    5.87           41.28           18.60             16.01
9        7450.0   13.81           21.20            7.15              6.56
10       3310.0    1.67        2,584.21              --                --
11       1400.0   11.64          -17.00          -15.34             14.20
12       7575.0    1.75           22.32           -3.89             -0.94
13        364.0    0.82           11.80           -9.71              2.90
14       1985.0    1.74           16.69           -8.83             -6.33
15       2700.0  133.88        1,385.76          -31.95            -35.14
16      90000.0   18.44            3.75           15.54              6.41
17       3750.0   33.40           -0.72            5.70              3.87
18      10375.0   27.17           19.98           17.40             12.76
19       3580.0   40.95          495.45            6.23              9.38

Joining both the column (idx stock code and the price code info)

In [100]:
concat_idx=pd.concat([df,df_financial],axis=1)

In [102]:
concat_idx.head(20)

,Idx,Company,Stock Price,PER,EPS Growth 1 Yr,EPS Growth 3 Yr,EPS Growth 5 Year
0,ADHI,Adhi Karya (Persero) Tbk.,1610.0,1.61,44.12,-7.47,7.75
1,ADRO,Adaro Energy Tbk.,1450.0,11.02,119.37,12.67,-10.76
2,AKRA,AKR Corporindo Tbk.,4740.0,26.98,-20.82,-11.95,1.46
3,ANTM,Aneka Tambang Tbk.,960.0,0.52,102.24,-57.89,-56.34
4,ASII,Astra International Tbk.,7250.0,18.56,4.78,-7.93,-3.15
5,BBCA,Bank Central Asia Tbk.,27525.0,23.38,14.36,13.04,13.48
6,BBNI,Bank Negara Indonesia (Persero) Tbk.,9350.0,10.31,25.30,7.90,14.32
7,BBRI,Bank Rakyat Indonesia (Persero) Tbk.,3990.0,15.08,11.70,8.70,8.87
8,BBTN,Bank Tabungan Negara (Persero) Tbk.,2390.0,5.87,41.28,18.60,16.01
9,BMRI,Bank Mandiri (Persero) Tbk.,7450.0,13.81,21.20,7.15,6.56
10,BRPT,Barito Pacific Tbk.,3310.0,1.67,"2,584.21",--,--
11,BSDE,Bumi Serpong Damai Tbk.,1400.0,11.64,-17.00,-15.34,14.20
12,CPIN,Charoen Pokphand Indonesia Tbk.,7575.0,1.75,22.32,-3.89,-0.94
13,ELSA,Elnusa Tbk.,364.0,0.82,11.80,-9.71,2.90
14,ERAA,Erajaya Swasembada Tbk.,1985.0,1.74,16.69,-8.83,-6.33
15,EXCL,XL Axiata Tbk.,2700.0,133.88,"1,385.76",-31.95,-35.14
16,GGRM,Gudang Garam Tbk.,90000.0,18.44,3.75,15.54,6.41
17,HMSP,H.M. Sampoerna Tbk.,3750.0,33.40,-0.72,5.70,3.87
18,ICBP,Indofood CBP Sukses Makmur Tbk.,10375.0,27.17,19.98,17.40,12.76
19,INCO,Vale Indonesia Tbk.,3580.0,40.95,495.45,6.23,9.38

In [144]:
concat_idx=concat_idx.replace({'--':np.nan})
concat_idx=concat_idx.replace({',':''})

import numpy as np
PER=[str(i).replace(',','') for i in concat_idx['PER']]
PER=[i.replace('--','np.nan') for i in concat_idx['PER']]

In [145]:
concat_idx['PER']=[float(i) for i in concat_idx['PER']]

In [146]:
concat_idx.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 45 entries, 0 to 44
Data columns (total 7 columns):
Idx                  45 non-null object
Company              45 non-null object
Stock Price          45 non-null float64
PER                  44 non-null float64
EPS Growth 1 Yr      45 non-null object
EPS Growth 3 Yr      43 non-null object
EPS Growth 5 Year    41 non-null object
dtypes: float64(2), object(5)
memory usage: 2.8+ KB

In [193]:
concat_idx['EPS Growth 1 Yr']=concat_idx['EPS Growth 1 Yr'].astype(float)
concat_idx['EPS Growth 3 Yr']=concat_idx['EPS Growth 3 Yr'].astype(float)
concat_idx['EPS Growth 5 Year']=concat_idx['EPS Growth 5 Year'].astype(float)

In [194]:
concat_idx[['EPS Growth 1 Yr','EPS Growth 3 Yr','EPS Growth 5 Year']]=concat_idx[['EPS Growth 1 Yr','EPS Growth 3 Yr','EPS Growth 5 Year']].astype(float)

In [158]:
concat_idx.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 45 entries, 0 to 44
Data columns (total 7 columns):
Idx                  45 non-null object
Company              45 non-null object
Stock Price          45 non-null float64
PER                  44 non-null float64
EPS Growth 1 Yr      43 non-null float64
EPS Growth 3 Yr      43 non-null float64
EPS Growth 5 Year    41 non-null float64
dtypes: float64(5), object(2)
memory usage: 2.8+ KB

In [107]:
PER_df=pd.DataFrame(PER)

In [165]:
concat_idx['PEG 1 year']=round(concat_idx['PER']/concat_idx['EPS Growth 1 Yr'],2)
concat_idx['PEG 5 year']=round(concat_idx['PER']/concat_idx['EPS Growth 5 Year'],2)
concat_idx['PEG 3 year']=round(concat_idx['PER']/concat_idx['EPS Growth 3 Yr'],2)

In [166]:
concat_idx

,Idx,Company,Stock Price,PER,EPS Growth 1 Yr,EPS Growth 3 Yr,EPS Growth 5 Year,PEG 1 year,PEG 5 year,PEG 3 year
0,ADHI,Adhi Karya (Persero) Tbk.,1610.0,1.61,-7.47,-7.47,7.75,-0.22,0.21,-0.22
1,ADRO,Adaro Energy Tbk.,1450.0,11.02,12.67,12.67,-10.76,0.87,-1.02,0.87
2,AKRA,AKR Corporindo Tbk.,4740.0,26.98,-11.95,-11.95,1.46,-2.26,18.48,-2.26
3,ANTM,Aneka Tambang Tbk.,960.0,0.52,-57.89,-57.89,-56.34,-0.01,-0.01,-0.01
4,ASII,Astra International Tbk.,7250.0,18.56,-7.93,-7.93,-3.15,-2.34,-5.89,-2.34
5,BBCA,Bank Central Asia Tbk.,27525.0,23.38,13.04,13.04,13.48,1.79,1.73,1.79
6,BBNI,Bank Negara Indonesia (Persero) Tbk.,9350.0,10.31,7.90,7.90,14.32,1.31,0.72,1.31
7,BBRI,Bank Rakyat Indonesia (Persero) Tbk.,3990.0,15.08,8.70,8.70,8.87,1.73,1.70,1.73
8,BBTN,Bank Tabungan Negara (Persero) Tbk.,2390.0,5.87,18.60,18.60,16.01,0.32,0.37,0.32
9,BMRI,Bank Mandiri (Persero) Tbk.,7450.0,13.81,7.15,7.15,6.56,1.93,2.11,1.93
10,BRPT,Barito Pacific Tbk.,3310.0,1.67,NaN,NaN,NaN,NaN,NaN,NaN
11,BSDE,Bumi Serpong Damai Tbk.,1400.0,11.64,-15.34,-15.34,14.20,-0.76,0.82,-0.76
12,CPIN,Charoen Pokphand Indonesia Tbk.,7575.0,1.75,-3.89,-3.89,-0.94,-0.45,-1.86,-0.45
13,ELSA,Elnusa Tbk.,364.0,0.82,-9.71,-9.71,2.90,-0.08,0.28,-0.08
14,ERAA,Erajaya Swasembada Tbk.,1985.0,1.74,-8.83,-8.83,-6.33,-0.20,-0.27,-0.20
15,EXCL,XL Axiata Tbk.,2700.0,133.88,-31.95,-31.95,-35.14,-4.19,-3.81,-4.19
16,GGRM,Gudang Garam Tbk.,90000.0,18.44,15.54,15.54,6.41,1.19,2.88,1.19
17,HMSP,H.M. Sampoerna Tbk.,3750.0,33.40,5.70,5.70,3.87,5.86,8.63,5.86
18,ICBP,Indofood CBP Sukses Makmur Tbk.,10375.0,27.17,17.40,17.40,12.76,1.56,2.13,1.56
19,INCO,Vale Indonesia Tbk.,3580.0,40.95,6.23,6.23,9.38,6.57,4.37,6.57
20,INDF,Indofood Sukses Makmur Tbk.,7275.0,18.47,25.72,25.72,4.32,0.72,4.28,0.72
21,INDY,Indika Energy Tbk.,2060.0,1.89,NaN,NaN,NaN,NaN,NaN,NaN
22,INKP,Indah Kiat Pulp & Paper Tbk.,10200.0,1.25,-2.85,-2.85,66.11,-0.44,0.02,-0.44
23,INTP,Indocement Tunggal Prakarsa Tbk.,19525.0,1.04,-8.25,-8.25,1.48,-0.13,0.70,-0.13
24,ITMG,Indo Tambangraya Megah Tbk.,22825.0,6.72,62.33,62.33,5.66,0.11,1.19,0.11
25,JSMR,Jasa Marga (Persero) Tbk.,5300.0,0.95,22.47,22.47,9.48,0.04,0.10,0.04
26,KLBF,Kalbe Farma Tbk.,1515.0,33.33,6.21,6.21,9.03,5.37,3.69,5.37
27,LPPF,Matahari Department Store Tbk.,4140.0,12.99,20.65,20.65,34.11,0.63,0.38,0.63
28,MEDC,Medco Energi Internasional Tbk.,875.0,0.74,74.25,74.25,14.87,0.01,0.05,0.01
29,MNCN,Media Nusantara Citra Tbk.,825.0,1.38,-6.34,-6.34,4.54,-0.22,0.30,-0.22
30,PGAS,Perusahaan Gas Negara (Persero) Tbk.,2410.0,11.72,-8.74,-8.74,-17.64,-1.34,-0.66,-1.34
31,PTBA,Bukit Asam Tbk.,4050.0,8.97,4.99,4.99,-6.60,1.80,-1.36,1.80
32,PTPP,PP (Persero) Tbk.,2090.0,1.48,25.97,25.97,28.48,0.06,0.05,0.06
33,PWON,Pakuwon Jati Tbk.,685.0,17.82,13.83,13.83,32.10,1.29,0.56,1.29
34,SCMA,Surya Citra Media Tbk.,1745.0,0.63,5.46,5.46,1.79,0.12,0.35,0.12
35,SMGR,Semen Indonesia (Persero) Tbk.,13025.0,12.04,-28.71,-28.71,-16.11,-0.42,-0.75,-0.42
36,SRIL,Sri Rejeki Isman Tbk.,340.0,0.68,26.12,26.12,17.59,0.03,0.04,0.03
37,TKIM,Pabrik Kertas Tjiwi Kimia Tbk.,11825.0,0.60,-43.02,-43.02,-41.13,-0.01,-0.01,-0.01
38,TLKM,Telekomunikasi Indonesia (Persero) Tbk.,3780.0,21.44,10.00,10.00,11.82,2.14,1.81,2.14
39,TPIA,Chandra Asri Petrochemical Tbk.,5600.0,0.82,158.43,158.43,NaN,0.01,NaN,0.01
40,UNTR,United Tractors Tbk.,27500.0,9.22,42.39,42.39,18.14,0.22,0.51,0.22
41,UNVR,Unilever Indonesia Tbk.,49125.0,56.77,6.09,6.09,8.95,9.32,6.34,9.32
42,WIKA,Wijaya Karya (Persero) Tbk.,1990.0,1.88,13.49,13.49,13.18,0.14,0.14,0.14
43,WSBP,Waskita Beton Precast Tbk.,392.0,NaN,2.10,2.10,NaN,NaN,NaN,NaN
44,WSKT,Waskita Karya (Persero) Tbk.,1930.0,1.59,76.59,76.59,51.15,0.02,0.03,0.02

saham pilihan dengan metode GARP dengan nilai PERG yang makin mengecil dari tahun ke tahun

In [186]:
df_new=concat_idx[(concat_idx['PEG 1 year']>concat_idx['PEG 5 year']) & (concat_idx['PEG 1 year']>0) & (concat_idx['PEG 5 year']>0)]

In [184]:
concat_idx['delta PEG']=concat_idx['PEG 1 year']-concat_idx['PEG 5 year']

In [185]:
concat_idx

,Idx,Company,Stock Price,PER,EPS Growth 1 Yr,EPS Growth 3 Yr,EPS Growth 5 Year,PEG 1 year,PEG 5 year,PEG 3 year,delta PEG
0,ADHI,Adhi Karya (Persero) Tbk.,1610.0,1.61,-7.47,-7.47,7.75,-0.22,0.21,-0.22,-0.43
1,ADRO,Adaro Energy Tbk.,1450.0,11.02,12.67,12.67,-10.76,0.87,-1.02,0.87,1.89
2,AKRA,AKR Corporindo Tbk.,4740.0,26.98,-11.95,-11.95,1.46,-2.26,18.48,-2.26,-20.74
3,ANTM,Aneka Tambang Tbk.,960.0,0.52,-57.89,-57.89,-56.34,-0.01,-0.01,-0.01,0.00
4,ASII,Astra International Tbk.,7250.0,18.56,-7.93,-7.93,-3.15,-2.34,-5.89,-2.34,3.55
5,BBCA,Bank Central Asia Tbk.,27525.0,23.38,13.04,13.04,13.48,1.79,1.73,1.79,0.06
6,BBNI,Bank Negara Indonesia (Persero) Tbk.,9350.0,10.31,7.90,7.90,14.32,1.31,0.72,1.31,0.59
7,BBRI,Bank Rakyat Indonesia (Persero) Tbk.,3990.0,15.08,8.70,8.70,8.87,1.73,1.70,1.73,0.03
8,BBTN,Bank Tabungan Negara (Persero) Tbk.,2390.0,5.87,18.60,18.60,16.01,0.32,0.37,0.32,-0.05
9,BMRI,Bank Mandiri (Persero) Tbk.,7450.0,13.81,7.15,7.15,6.56,1.93,2.11,1.93,-0.18
10,BRPT,Barito Pacific Tbk.,3310.0,1.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,BSDE,Bumi Serpong Damai Tbk.,1400.0,11.64,-15.34,-15.34,14.20,-0.76,0.82,-0.76,-1.58
12,CPIN,Charoen Pokphand Indonesia Tbk.,7575.0,1.75,-3.89,-3.89,-0.94,-0.45,-1.86,-0.45,1.41
13,ELSA,Elnusa Tbk.,364.0,0.82,-9.71,-9.71,2.90,-0.08,0.28,-0.08,-0.36
14,ERAA,Erajaya Swasembada Tbk.,1985.0,1.74,-8.83,-8.83,-6.33,-0.20,-0.27,-0.20,0.07
15,EXCL,XL Axiata Tbk.,2700.0,133.88,-31.95,-31.95,-35.14,-4.19,-3.81,-4.19,-0.38
16,GGRM,Gudang Garam Tbk.,90000.0,18.44,15.54,15.54,6.41,1.19,2.88,1.19,-1.69
17,HMSP,H.M. Sampoerna Tbk.,3750.0,33.40,5.70,5.70,3.87,5.86,8.63,5.86,-2.77
18,ICBP,Indofood CBP Sukses Makmur Tbk.,10375.0,27.17,17.40,17.40,12.76,1.56,2.13,1.56,-0.57
19,INCO,Vale Indonesia Tbk.,3580.0,40.95,6.23,6.23,9.38,6.57,4.37,6.57,2.20
20,INDF,Indofood Sukses Makmur Tbk.,7275.0,18.47,25.72,25.72,4.32,0.72,4.28,0.72,-3.56
21,INDY,Indika Energy Tbk.,2060.0,1.89,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,INKP,Indah Kiat Pulp & Paper Tbk.,10200.0,1.25,-2.85,-2.85,66.11,-0.44,0.02,-0.44,-0.46
23,INTP,Indocement Tunggal Prakarsa Tbk.,19525.0,1.04,-8.25,-8.25,1.48,-0.13,0.70,-0.13,-0.83
24,ITMG,Indo Tambangraya Megah Tbk.,22825.0,6.72,62.33,62.33,5.66,0.11,1.19,0.11,-1.08
25,JSMR,Jasa Marga (Persero) Tbk.,5300.0,0.95,22.47,22.47,9.48,0.04,0.10,0.04,-0.06
26,KLBF,Kalbe Farma Tbk.,1515.0,33.33,6.21,6.21,9.03,5.37,3.69,5.37,1.68
27,LPPF,Matahari Department Store Tbk.,4140.0,12.99,20.65,20.65,34.11,0.63,0.38,0.63,0.25
28,MEDC,Medco Energi Internasional Tbk.,875.0,0.74,74.25,74.25,14.87,0.01,0.05,0.01,-0.04
29,MNCN,Media Nusantara Citra Tbk.,825.0,1.38,-6.34,-6.34,4.54,-0.22,0.30,-0.22,-0.52
30,PGAS,Perusahaan Gas Negara (Persero) Tbk.,2410.0,11.72,-8.74,-8.74,-17.64,-1.34,-0.66,-1.34,-0.68
31,PTBA,Bukit Asam Tbk.,4050.0,8.97,4.99,4.99,-6.60,1.80,-1.36,1.80,3.16
32,PTPP,PP (Persero) Tbk.,2090.0,1.48,25.97,25.97,28.48,0.06,0.05,0.06,0.01
33,PWON,Pakuwon Jati Tbk.,685.0,17.82,13.83,13.83,32.10,1.29,0.56,1.29,0.73
34,SCMA,Surya Citra Media Tbk.,1745.0,0.63,5.46,5.46,1.79,0.12,0.35,0.12,-0.23
35,SMGR,Semen Indonesia (Persero) Tbk.,13025.0,12.04,-28.71,-28.71,-16.11,-0.42,-0.75,-0.42,0.33
36,SRIL,Sri Rejeki Isman Tbk.,340.0,0.68,26.12,26.12,17.59,0.03,0.04,0.03,-0.01
37,TKIM,Pabrik Kertas Tjiwi Kimia Tbk.,11825.0,0.60,-43.02,-43.02,-41.13,-0.01,-0.01,-0.01,0.00
38,TLKM,Telekomunikasi Indonesia (Persero) Tbk.,3780.0,21.44,10.00,10.00,11.82,2.14,1.81,2.14,0.33
39,TPIA,Chandra Asri Petrochemical Tbk.,5600.0,0.82,158.43,158.43,NaN,0.01,NaN,0.01,NaN
40,UNTR,United Tractors Tbk.,27500.0,9.22,42.39,42.39,18.14,0.22,0.51,0.22,-0.29
41,UNVR,Unilever Indonesia Tbk.,49125.0,56.77,6.09,6.09,8.95,9.32,6.34,9.32,2.98
42,WIKA,Wijaya Karya (Persero) Tbk.,1990.0,1.88,13.49,13.49,13.18,0.14,0.14,0.14,0.00
43,WSBP,Waskita Beton Precast Tbk.,392.0,NaN,2.10,2.10,NaN,NaN,NaN,NaN,NaN
44,WSKT,Waskita Karya (Persero) Tbk.,1930.0,1.59,76.59,76.59,51.15,0.02,0.03,0.02,-0.01

To see the most prospectful stock

In [192]:
df_new.sort_values('delta PEG',ascending=False)

,Idx,Company,Stock Price,PER,EPS Growth 1 Yr,EPS Growth 3 Yr,EPS Growth 5 Year,PEG 1 year,PEG 5 year,PEG 3 year,delta PEG
41,UNVR,Unilever Indonesia Tbk.,49125.0,56.77,6.09,6.09,8.95,9.32,6.34,9.32,2.98
19,INCO,Vale Indonesia Tbk.,3580.0,40.95,6.23,6.23,9.38,6.57,4.37,6.57,2.20
26,KLBF,Kalbe Farma Tbk.,1515.0,33.33,6.21,6.21,9.03,5.37,3.69,5.37,1.68
33,PWON,Pakuwon Jati Tbk.,685.0,17.82,13.83,13.83,32.10,1.29,0.56,1.29,0.73
6,BBNI,Bank Negara Indonesia (Persero) Tbk.,9350.0,10.31,7.90,7.90,14.32,1.31,0.72,1.31,0.59
38,TLKM,Telekomunikasi Indonesia (Persero) Tbk.,3780.0,21.44,10.00,10.00,11.82,2.14,1.81,2.14,0.33
27,LPPF,Matahari Department Store Tbk.,4140.0,12.99,20.65,20.65,34.11,0.63,0.38,0.63,0.25
5,BBCA,Bank Central Asia Tbk.,27525.0,23.38,13.04,13.04,13.48,1.79,1.73,1.79,0.06
7,BBRI,Bank Rakyat Indonesia (Persero) Tbk.,3990.0,15.08,8.70,8.70,8.87,1.73,1.70,1.73,0.03
32,PTPP,PP (Persero) Tbk.,2090.0,1.48,25.97,25.97,28.48,0.06,0.05,0.06,0.01